region: us-east-2
bucketDeploy: lambdas-stori-dev
environment:
  DATABASE: framework
  REGION: us-east-2
  SQL_HOST: ltdata.cj7i5sksfdfm.us-east-2.rds.amazonaws.com
  SQL_USER: lt
  SQL_PASSWORD: poropo1994
