version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - npm install --silent -g npm
      - npm install --silent -g serverless
  pre_build:
    commands:
      - cd lmds
      - serverless plugin install -n serverless-python-requirements
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
  build:
    commands:
      - serverless deploy --stage $ENVIRONMENT -v
artifacts:
  files:
    - lmds/**/*