service: storitest
app: stori-apps
frameworkVersion: '2'


provider:
  name: aws
  #runtime: python3.8
  lambdaHashingVersion: 20201221
  tags:
    servicio: test_stori
    proyecto: stori
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}
  deploymentBucket:
    name: ${self:custom.bucketDeploy}
    tags:
      Proceso: CI/CD
      Data: data-stori # Etiqueta que se usa para el ciclo de vida de los datos generados para el deploy.
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "ses:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

custom: ${file(config_deploy/config.${self:provider.stage}.yml)}

functions:
  stori:
    handler: idempotency/handler.start
    name: ${self:provider.stage}-LMD_stori_idempotency
    description: Idempotency lambda
    runtime: python3.7
    # events:
    #   - s3: ${self:custom.TRG_BUCKET}
    memorySize: 128
    timeout: 300    
    #vpc: ${self:custom.vpc} #checar
    environment: ${self:custom.environment}
    package:
      patterns:
        - '!config_deploy/**'
        - '!.serverless/**'
        - '!requirements.txt'
        - '!event.json'
        - '!serverless.yml'
        - '!README.md'
        - '!node_modules/**'
        - '!package-lock.json'
        - '!package.json'
  s3invoke:
    handler: process_file/invokeS3.start
    name: ${self:provider.stage}-LMD_invokeS3
    description: Idempotency lambda
    runtime: python3.7
    events:
      - s3: ${self:custom.TRG_BUCKET}
    memorySize: 128
    timeout: 300    
    #vpc: ${self:custom.vpc} #checar
    environment: ${self:custom.environment}
    package:
      patterns:
        - '!config_deploy/**'
        - '!.serverless/**'
        - '!requirements.txt'
        - '!event.json'
        - '!serverless.yml'
        - '!README.md'
        - '!node_modules/**'
        - '!package-lock.json'
        - '!package.json'
plugins:
  - serverless-python-requirements
